# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_reference', models.CharField(max_length=50)),
                ('item_source', models.CharField(max_length=50)),
                ('item_quantity', models.CharField(max_length=50)),
                ('item_Measurement', models.CharField(max_length=50)),
                ('item_unit_price', models.CharField(max_length=50)),
                ('item_total_price', models.CharField(max_length=50)),
            ],
        ),
    ]
