# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_quantity',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_total_price',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_unit_price',
            field=models.IntegerField(max_length=50),
        ),
    ]
