# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20161021_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_Measurement',
            new_name='item_measurement',
        ),
    ]
