# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_auto_20161021_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_quantity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_total_price',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_unit_price',
            field=models.CharField(max_length=50),
        ),
    ]
