# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_auto_20161026_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
