# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_item_item_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_category',
        ),
    ]
